import { Poppins } from "next/font/google"; // Import Poppins font
import "./globals.css";

// Load Poppins font with subsets and weights
const poppins = Poppins({
  variable: "--font-poppins", // Define a CSS variable for the font
  subsets: ["latin"], // Include the Latin subset
  weight: ["300", "400", "500", "600", "700"], // Include desired font weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}


// "use client";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Provider from "../components/providers/Provider";
// import Header from "@/components/header-comps/SdHeader";
// import SdSideBars from "@/components/sidebar-comps/SideBars";
// import { cn } from "@/lib/utils";
// import { usePathname } from "next/navigation";

// import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";

// const inter = Inter({ subsets: ["latin"] });

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const pathname = usePathname();
//   const isLoginPage = pathname === "/auth/login";
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className={cn("bg-[#F7F9FB] min-h-screen", inter.className)}>
//         <ReactQueryProvider>
//           <Provider>
//             {!isLoginPage && <Header />}
//             {!isLoginPage && <SdSideBars />}
//             <main
//               className={
//                 isLoginPage
//                   ? ""
//                   : "flex-grow ml-20 mr-8 mt-7 mb-7 overflow-x-auto scroll-smooth"
//               }
//             >
//               {children}
//             </main>
//           </Provider>
//         </ReactQueryProvider>
//       </body>
//     </html>
//   );
// }
